### ISSUE TITLE
Add Alien Turret

### ISSUE THREAD

**Issue by renoth** [renoth/factorio-alien-module#10]
A new building should be added : alien turret

Possible features:
- Range increases with Level (evaluate if possible)
- Damage increases with Level
- Shooting Speed increases with Level

**Comment by demongo1154** [comment]
that would be cool, the more alien stuff the better :)

**Comment by unhott** [comment]
I like this idea-- I think the range / damage / shooting speed increases with level would have to be performed just like the hypermodule creation is, which is not ideal but it seems feasible.
