### ISSUE TITLE
Error loading the mod

### ISSUE THREAD

**Issue by ArmorAssassine** [renoth/factorio-alien-module#101]
When I start the game and it checks the mods then the error occurs

"Error while loading entity prototype "alien-wall" (wall): Key "icon_size" not found in property tree at ROOT.wall.alien-wall Modifications: Alien Loot Economy

Can you please fix this.[
![Bild_2024-10-06_131422778](https://github.com/user-attachments/assets/36bdb6ed-fac4-4136-8eab-d25c7a93d1fc)
](url)

**Comment by renoth** [comment]
Do you have any other mods acitve? If yes, which ones?

**Comment by ArmorAssassine** [comment]
I have many mods active. I got the reloaded mod and it works. The only
problem I could find was the Loot Chest + mod had spun with it because no
artifacts were spawned.

Am So., 6. Okt. 2024 um 20:50 Uhr schrieb Johannes Renoth <
***@***.***>:

**Comment by renoth** [comment]
Does the error occur if you only have this mod active?
