### ISSUE TITLE
Compatibility for Factorio 2.0

### ISSUE THREAD

**Issue by maxxcz69** [renoth/factorio-alien-module#102]
Hello, are you going to update this mod for Factorio 2.0 ?

**Comment by renoth** [comment]
Yes, but there are some issues at the moment with the changes in 2.0

**Comment by renoth** [comment]
2.0.0 is released, please test.

**Comment by bdlus** [comment]
Error on update. no other mod installed. 

![Screenshot 2024-10-21 205546](https://github.com/user-attachments/assets/35d95c06-7493-442d-9308-a4aa98f47cd5)

**Comment by AlanBirch** [comment]
Exact same isue here. as bdlus. ^ when killed amount required to upgrade modules, game crashes. (2.0 + Space age)

**Comment by maxxcz69** [comment]
Great thank you

Dne út 22. 10. 2024 4:31 uživatel AlanBirch ***@***.***>
napsal:

**Comment by renoth** [comment]
Thanks for testing, it seems that Factorio 2.0 has lots of breaking changes in the modding API, request_slot_count was removed and i dont know the replacement

**Comment by renoth** [comment]
2.0.1 : Disabled that feature for now

**Comment by bdlus** [comment]
![Screenshot 2024-10-22 090322](https://github.com/user-attachments/assets/d650c8ed-73f6-46d6-920d-e2e3d69b3510)
from the menu screen. didn't even get to load.

**Comment by Tenderroast** [comment]
it seems that the non-hyper modules aren't progressing past tier 1

**Comment by AlanBirch** [comment]
As I quick tried now, the version 2.0.1 works for module upgrading, so thx so much for quick fix! but I just noticed another weird isue... when changing max amount ore that can drop from enemies and bases, and setting max drop from enemies to 0.. it somehow drops sometimes up to 100 ore....

**Comment by AlanBirch** [comment]
> it seems that the non-hyper modules aren't progressing past tier 1

check changelog.. they have been removed amog other things

**Comment by AlanBirch** [comment]
> As I quick tried now, the version 2.0.1 works for module upgrading, so thx so much for quick fix! but I just noticed another weird isue... when changing max amount ore that can drop from enemies and bases, and setting max drop from enemies to 0.. it somehow drops sometimes up to 100 ore....

Not sure if I understand it correctly, but by looking into your data.lua it seems that in AddLootToVanillaEnemies() you're using fixed max drop amount values rather than variable from settings.lua; hope it helps :D

**Comment by JadedMagic5** [comment]
> Error on update. no other mod installed.
> 
> ![Screenshot 2024-10-21 205546](https://private-user-images.githubusercontent.com/185870111/378652881-35d95c06-7493-442d-9308-a4aa98f47cd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQxODEsIm5iZiI6MTcyOTY2Mzg4MSwicGF0aCI6Ii8xODU4NzAxMTEvMzc4NjUyODgxLTM1ZDk1YzA2LTc0OTMtNDQyZC05MzA4LWE0YWE5OGY0N2NkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwNjExMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzdiZTc4OTc1ZTI5YmFlZDY3ZGQyOTAyMmE3YjAxNWQxYWY1NzdmZjQ0MDc0Y2U5OWQxZTBlMmRkNjEwZjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MESZy15YsAxZu6O9BEIsSqZBHRFpxPt8D0v0W2rV5r0)

I get the same error when loading my save, mod works fine on a new game though.

**Comment by renoth** [comment]
Please test 2.0.2 just released, should be fixed now

**Comment by JadedMagic5** [comment]
My loaded save works good now, got to hyper level 1.06 as well, no crash. Thanks renoth!
Your mod has been a long-lasting favorite of mine.

**Comment by maxxcz69** [comment]
hello, 
hypermodules cant be inserted into factories. its bug or right feature?

**Comment by s1mplu** [comment]
UP - make the "quality" effect of the modules optional, as the appearance of any quality above normal items can lock up production lines if not planned for. (Thanks for your mod. I've been enjoying it for a long time.)   ---- yes please!

**Comment by renoth** [comment]
Quality can now be turned off in 2.0.3 :) Thanks for reporting and playtesting ;)

**Comment by renoth** [comment]
> Hi, I can only use the hypermodules on intermediate products since recently. It's possible to place them in an assembler or smelter that has no recipe set yet and then set them but they disappear when you save like this and then load. I would also like to request to make the "quality" effect of the modules optional, as the appearance of any quality above normal items can lock up production lines if not planned for. (Thanks for your mod. I've been enjoying it for a long time.)

I think that was a change in Factorio 2.0.11 but i am not sure

**Comment by renoth** [comment]
Added https://mods.factorio.com/mod/Productivity as a necessary dependency for this mod. The aforementioned mod makes Factorio with alien loot economy behave as before patch 2.0.11 (enabling productivity on final products again)

**Comment by renoth** [comment]
2.0.4 released with the productivity fix

**Comment by s1mplu** [comment]
thank you very much

**Comment by maxxcz69** [comment]
A issue/bug happen to me when hypermodule lvlup. Every module which is above common turned into common verison.

**Comment by renoth** [comment]
> A issue/bug happen to me when hypermodule lvlup. Every module which is above common turned into common verison. and sometimes when hypermodule is in the foundry, it disapears.

Should be fixed in 2.0.5

**Comment by renoth** [comment]
I havent unlocked the foundry yet, so i cannot playtest it ;), i will playtest when i get there ...
Or you can submit a pull request to fix the issue

**Comment by maxxcz69** [comment]
my hypermodule are multiplied in invterory, maybe during lvlup (RPG mode)

**Comment by Summonerd** [comment]
![image](https://github.com/user-attachments/assets/98a73fe0-7f80-488f-a271-a95b26936be3)
Just had this crash, guess it was at levelup.

**Comment by maxxcz69** [comment]
hypermodule is too heavy to launch it via rocket to the space

**Comment by Summonerd** [comment]
I'm still getting the crash from my last screenshot when I reach level 25 despite the patches. Does it maybe have to do with Wube changing the max productivity to 300% or something? Anyone else here get the same crash?

**Comment by renoth** [comment]
> I'm still getting the crash from my last screenshot when I reach level 25 despite the patches. Does it maybe have to do with Wube changing the max productivity to 300% or something? Anyone else here get the same crash?

Maybe that is the case but if i insert hypermodules level 100 in an assembler 3 the productivity is just capped at 300%

![image](https://github.com/user-attachments/assets/38867b59-c489-4b67-8ce6-fff3183783ff)

Maybe there is an error in the LUA API, i dont know.

what is your productivity in the assembler before the crash? level 25 should have 25% productivity bonus each, so you would need 12 modules to reach 300%

**Comment by Summonerd** [comment]
I have nothing with more than 2 modules. I'm also making the hyper ammo all the time though. I've tried disabling a bunch of mods that might be affecting it but the crash still happens. Want me to send you the save? It's about 20 seconds before the crash.

**Comment by maxxcz69** [comment]
It is normal feature, that beacon decrease quality of afected fatories and foundries? And this debuff is applied for quality module too...?

**Comment by renoth** [comment]
Speed modules do decrease quality if that is what you are using inside beaons ;)

**Comment by maxxcz69** [comment]
ok, thank you

**Comment by Jester18514** [comment]
![image](https://github.com/user-attachments/assets/e333f25e-2a5f-4d77-ad45-e9043f260cdb)

First, I just want to say thanks for all the work on this mod - I've thoroughly enjoyed it over the last few years and was very excited when you updated it for 2.0.

The mod has been working very well for me through this playthrough up until last night when I had the same issue as others above. When I went from Lvl 44 to lvl 45 I got the error message in the screenshot. I thought it might have something to do with my settings (I play with 0.2 level exponent and 0.2 on the module effect), so I changed the module effect to 0.015 to see if that would prevent me from hitting some random cap I didn't know about. This still produced the same error.

The only other thing that was different about this level up vs. others is that I had my modules in the Foundry and Electromagnetic machine, but I tried removing them from there and still had the same error, so I'm at a bit of a loss.

For troubleshooting, the other mods I have loaded are:
AAI Containers & Warehouses
AAI Loaders
Adaptive Movement Speed
Alien Loot Economy
Cursor Craft
Even Distribution
Factorio Library
Factory Planner
Far Reach
Fill4Me
Fox TODO
Jetpack
Quality of Life Research
Rate Calculator
Show Max Underground Distance
Squeak Through 2
Total Productivity for belts, landfill & everything.

let me know if you need more info.
Thanks again!
