### ISSUE TITLE
Error while running setup for entity prototype "deg-battery-charging-station" (assembling-machine): next_upgrade target (alien-accumulator) 

### ISSUE THREAD

**Issue by simbiant** [renoth/factorio-alien-module#103]
Error while mod "[Electric Trains](https://mods.factorio.com/mod/ElectricTrains)" installed. I duplicate bug report to them because I don't know who has to fix it

**Comment by renoth** [comment]
Which error? Without any futher information i cannot help you

**Comment by simbiant** [comment]
Error while loading game

**Comment by simbiant** [comment]
I activate this 2 mods and when press confirm, game restarts. And it shows error while loading

**Comment by renoth** [comment]
Yes but what does the error say?

**Comment by simbiant** [comment]
![image](https://github.com/user-attachments/assets/22daf247-09ec-457d-8a73-c5541411783a)

**Comment by simbiant** [comment]
Oh, looks like title was not fully paste

**Comment by simbiant** [comment]
Here screenshot

**Comment by renoth** [comment]
That looks like an error in the Electric Trains mod

**Comment by simbiant** [comment]
![image](https://github.com/user-attachments/assets/eb89d02d-7691-4a45-9742-6fe9805b467c)

**Comment by renoth** [comment]
i can define electric trains as an optional dependency so that their scripts run first.

**Comment by renoth** [comment]
please test with the latest version

**Comment by simbiant** [comment]
Yeah, it works. Thx
