### ISSUE TITLE
non-recoverable error

### ISSUE THREAD

**Issue by s1mplu** [renoth/factorio-alien-module#105]
![image](https://github.com/user-attachments/assets/1f891bbe-9ea2-4ab7-8e73-5b9d94cb6445)

**Comment by ZorGRiP** [comment]
The same error occurred when switching from LVL 42 to LVL 43.
There is no error on the Alien Loot Economy 2.0.7 version.

**Comment by s1mplu** [comment]
How to change version?

**Comment by renoth** [comment]
You can select previous downloaded versions from the mod-settings. Or you can manually download older versions from the mod portal.

**Comment by renoth** [comment]
Please Test version 2.0.8
