### ISSUE TITLE
Module/Plate weight (for SA rocket shipping purpose)

### ISSUE THREAD

**Issue by Khornar** [renoth/factorio-alien-module#106]
There is new Space Age parameter "weight" in item description lua.
If left undefined, rocket defaults to one full stack per rocket.
And it derives weight of hyper module from materials used to craft, so modules from level 11 (220 plates to craft) onwards are too heavy for shipping.
Even if rocket capacity is altered with mods, it still changes nothing, since it defaults to one stack anyway.

Altering local copy of alien-module.lua by adding line "    weight = 20 * kg," after "	stack_size = 50," and it solved that issue. 

Not sure if it's too easy, maybe defining weight of plates to 0.5kg, while leaving module weight undefined to allow shiping modules up to lvl 100 (even if only single module per rocket) is a better solution.

**Comment by renoth** [comment]
Thanks for the info, what is the maximum weight a rocket can carry at once?

**Comment by renoth** [comment]
Should be fixed in 2.0.10

**Comment by Khornar** [comment]
> Thanks for the info, what is the maximum weight a rocket can carry at once?

1000kg aka 1 tonn by default.
