### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by sloshappy** [renoth/factorio-alien-module#108]
Crashes even after starting an older save when it gets around the same amount of time.

The mod Alien Loot Economy (2.0.10) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event alien-module::on_nth_tick(600)
Bonus progress can't be negative.
stack traceback:
	[C]: in function '__newindex'
	__alien-module__/control.lua:284: in function 'update_recipes'
	__alien-module__/control.lua:466: in function <__alien-module__/control.lua:423>

**Comment by sloshappy** [comment]
Tried to start a new game, same thing eventually happens.

**Comment by renoth** [comment]
Do you have other mods active?

**Comment by sloshappy** [comment]
Ya a ton, I was just making sure it wasnt something you needed to know. It is honestly fine, I think I am done with factorio for a few weeks to let everyone get some patches on their mods and stuff. Having a lot of cross fail issues.
