### ISSUE TITLE
the number of kills and progress and level button in 1 window pls

### ISSUE THREAD

**Issue by s1mplu** [renoth/factorio-alien-module#109]
![image](https://github.com/user-attachments/assets/53aca790-8afa-4d64-9e5c-5913f672d9ca)
can you please make these two, to be just one? and a little smaller if possible. Thank you very much and I greatly appreciate the mod you created! keep it up

**Comment by renoth** [comment]
Those are two different mods so it is not possible

**Comment by s1mplu** [comment]
ok, i understand . but.... ur hypermodule window can it be a little smaller?

**Comment by renoth** [comment]
Yes i can try to make it a bit smaller
