### ISSUE TITLE
Will you make any big updates to the mod?

### ISSUE THREAD

**Issue by miricha** [renoth/factorio-alien-module#110]
I didn't know where to ask this,

But do you plan to expand the mod by adding new stuff like an alien pumpjack, alien pipes and pump, big alien mining drill, alien beacon, etc. Everything can be more expensive to craft for some balance and the alien steel plate can be brought back for some new recipes.

**Comment by renoth** [comment]
No at the moment i do not plan to expand the mod significatnly since i dont have the time
