### ISSUE TITLE
Only mod loaded, this happens eventually

### ISSUE THREAD

**Issue by sloshappy** [renoth/factorio-alien-module#111]
The mod Alien Loot Economy (2.0.11) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event alien-module::on_nth_tick(600)
Bonus progress can't be negative.
stack traceback:
	[C]: in function '__newindex'
	__alien-module__/control.lua:284: in function 'update_recipes'
	__alien-module__/control.lua:466: in function <__alien-module__/control.lua:423>

So I reported this before, but I totally didnt think of trying the game with just this mod. So with just this mod, this eventually happens.

**Comment by renoth** [comment]
please try 2.0.12

**Comment by sloshappy** [comment]
Yep you squashed that bug!
