### ISSUE TITLE
[Error v2.0.11] - Overflow of the progress bonus (quality?)

### ISSUE THREAD

**Issue by AGDMExM** [renoth/factorio-alien-module#112]
This error occurs at the 84th level of the module. 
![image](https://github.com/user-attachments/assets/78f7d76f-e4e7-4220-9de1-5c39a962313e)
There is an assumption that this is due to an overflow of the maximum quality value (perhaps it is worth limiting how in productivity == 300?) 

I can't say for sure which factory caused this to happen to the modules

**Comment by renoth** [comment]
maybe fixed in 2..12

**Comment by AGDMExM** [comment]
> maybe fixed in 2..12

thx
