### ISSUE TITLE
Possible way to improve update procedure

### ISSUE THREAD

**Issue by Pialex99** [renoth/factorio-alien-module#12]
Hi, looking around on some mods code I came up on this one
https://mods.factorio.com/mod/crafting-efficiency
which use the omnilib to automatically update reciepes on assemblers as soon as a new version of them is unlock (through research but through script should be fine as well, I think), maybe you can find a way to update de modules effects as well.
Hope to have helped you

**Comment by renoth** [comment]
The current system works fine, thanks for the suggestion though.
