### ISSUE TITLE
Alien ore cannot be smelted

### ISSUE THREAD

**Issue by Hitwood** [renoth/factorio-alien-module#16]
Hi,
since the last update i receive tthis message every timne i try to put alien ore in a furnance.

**Comment by demongo1154** [comment]
strange... well with factorio 17 set to release in under 10days so I feel it may get fixed after then...

**Comment by renoth** [comment]
I can remember reading about this issue a while ago, iirc it was due to another mod. Please disable all other mods and try again.

**Comment by renoth** [comment]
cannot reproduce this issue

**Comment by Hitwood** [comment]
The mod was updated before the factorio release of 0.17. After this it worked fine, till yesterday it also worked fine. After the last update it doesn´t work again. I´m not sure after the update of factorio or the update of this mod, because both were released pretty at the same time.

**Comment by renoth** [comment]
I am very certain that this is not an issue of this mod but of another mod. **Please disable all other mods and try again**. If the problem persists contact me.

**Comment by renoth** [comment]
You could also provide a list of all active mods that are in use.

**Comment by Hitwood** [comment]
I disabled all mods and enabled them step by step. It works again :)
Strange....

Am Sa., 2. März 2019 um 17:12 Uhr schrieb renoth <notifications@github.com>:
