### ISSUE TITLE
im adding a new type of hyper module to the mod:

### ISSUE THREAD

**Issue by demongo1154** [renoth/factorio-alien-module#17]
[alien-module_0.5.4.zip](https://github.com/renoth/factorio-alien-module/files/2872422/alien-module_0.5.4.zip)

editing the mod by adding another type of hyper module that's green focused vice production, getting errors on world load/gen vice during startup I am semi-new to this what am I doing wrong?

**Comment by demongo1154** [comment]
my discord username is: demongo1154#2812

**Comment by wawa1474** [comment]
You have to check and update the module type individually, while I haven't loaded the game with the file I'm uploading I'm pretty sure I've fixed all the errors.

In the future make sure you also include the errors you get to make it easier to fix the bugs that caused them.

if you have anymore issues don't be afraid to ask for more help :)

[alien-module_0.5.4.zip](https://github.com/renoth/factorio-alien-module/files/2872469/alien-module_0.5.4.zip)

**Comment by demongo1154** [comment]
sweet, thanks :)

**Comment by demongo1154** [comment]
will do one of my gaming pals showed me this so id figure id use it ;)

**Comment by demongo1154** [comment]
![image](https://user-images.githubusercontent.com/47702270/52907223-71bd0280-3222-11e9-94fb-cd2c1756f5a1.png)
close...

**Comment by demongo1154** [comment]
at least now I have a place to look :)

**Comment by renoth** [comment]
I wont implement new features before 0.17 comes out and the first new version will probably be making this mod compatible with 0.17 asap. After that it could be looked into.

**Comment by wawa1474** [comment]
okay, got all the errors fixed now it's down to just fiddling with the values for the module effects to get what is wanted.

[alien-module_0.5.4.zip](https://github.com/renoth/factorio-alien-module/files/2872983/alien-module_0.5.4.zip)

**Comment by renoth** [comment]
0.17 is out, can you provide a PR for your proposed changes?

**Comment by demongo1154** [comment]
updated mine so far so good if ya want I can share it here I made it for the times that productivity is not allowed...

**Comment by demongo1154** [comment]
also tweeked mine in terms of tech and cost...

**Comment by demongo1154** [comment]
[alien-module_0.6.2.zip](https://github.com/renoth/factorio-alien-module/files/2932093/alien-module_0.6.2.zip)
not entirely sure how to make a PR, i did change leveling scaling a bit just ignore that part...

**Comment by renoth** [comment]
Thanks, i will take a look at it this weekend

**Comment by demongo1154** [comment]
sweet :)

**Comment by demongo1154** [comment]
[alien-module_0.6.4.zip](https://github.com/renoth/factorio-alien-module/files/2986029/alien-module_0.6.4.zip)
works but its very-very laggey, sometimes the game after being froze 8+seconds just closes with no report...
