### ISSUE TITLE
Hypermodules inside beacons don't get upgraded on level up

### ISSUE THREAD

**Issue by barskykd** [renoth/factorio-alien-module#18]
This mod https://mods.factorio.com/mod/UnrestrictedProductivityModule allows to place any modules in beacons. If I place hypermodules in beacons - they aren't upgraded on level up.

**Comment by wawa1474** [comment]
Here's a quick-fix.
hyper modules in beacons will now also be upgraded.

[alien-module_0.5.4.zip](https://github.com/renoth/factorio-alien-module/files/2875854/alien-module_0.5.4.zip)

**Comment by wawa1474** [comment]
I've updated my fork to include the beacon module updating as well.

https://github.com/wawa1474/factorio-alien-module/tree/update-beacon-modules

**Comment by barskykd** [comment]
Thanks for quick fix! 👍

**Comment by renoth** [comment]
Fixed with 0.5.5. Thanks for the fix and the report!
