### ISSUE TITLE
Want to add some new feature

### ISSUE THREAD

**Issue by eKi-peTer** [renoth/factorio-alien-module#2]
Hello, love your mod and its great.
But i think it would be amazing to use the currentmodulelevel to increase the damage and the ingredients for the alien-magazine to. Or for the solarpanels and mining-drill. That would be awesome.
If i add this: `ingredients =
    {
      {"alien-plate", 2 * i}, {"iron-plate", 6 * i}, {"copper-plate", 1 * i}
    },`
the "i" is always 100 or zero. can you help me plz.

**Comment by renoth** [comment]
I am sorry without seeing the whole code it is hard to help. You can create a fork and make your changes and we can discuss them in your fork.

**Comment by eKi-peTer** [comment]
Thanks for your answer, I think i fixed the problem. I love the idee, increase the stats by killing biters.
[alien-module_0.3.6.zip](https://github.com/renoth/factorio-alien-module/files/1115010/alien-module_0.3.6.zip)

**Comment by renoth** [comment]
Can you please make a Pull Request like in forking the project, making changes, committing these changes and then making a pull request to merge these changes back into the main repository?
