### ISSUE TITLE
Rampant compatibility: loot not registering

### ISSUE THREAD

**Issue by bzy-xyz** [renoth/factorio-alien-module#22]
Rampant 0.16.42 constructs factions in its `data-final-fixes.lua`, so when loot is registered in `data.lua` the Rampant enemies don't yet exist. Hence Rampant enemies never drop loot.

Related to but distinct from #8.

(Note: merely renaming `data.lua` will break e.g. AAI Industry's "Vehicle fuel from alien fuel" recipe.)

**Comment by renoth** [comment]
Ok so this mod must usw final fixes AS well. Then soon every mod will have to use final fixes.

**Comment by judos** [comment]
Hi @bzy-xyz, did you create a ticket in the rampant mod for this? Or is it fixed there already? I'm interested in starting a new map with both mods... Thanks for your help

**Comment by bzy-xyz** [comment]
Someone created a compatibility patch: https://mods.factorio.com/mod/rampant-alienmodule-compat

I'd suggest you use that instead of trying to do some sort of ideological warfare.

**Comment by judos** [comment]
nice that makes me happy that other people already thought of this ^^ Well creating factions in final-fixes is not an ideological discussion but just plain wrong :D but since rampant is not perfectly maintained i won't create an issue there.
