### ISSUE TITLE
Alien Loot Economy Migration error

### ISSUE THREAD

**Issue by Solarwuff** [renoth/factorio-alien-module#27]
I got the following error when trying to migrate a 0.16 save game to 0.17

<img width="455" alt="Capture" src="https://user-images.githubusercontent.com/49283198/55568305-c0a1f700-56ff-11e9-8b3e-52a78ea26439.PNG">

**Comment by demongo1154** [comment]
the base game updated a tech name from "electric-energy-accumulators-1" to just "electric-energy-accumulators" some modded save will have trouble migrating versions...

**Comment by renoth** [comment]
someone in the forums reported this as fixed? is this true?

**Comment by zelitz** [comment]
> someone in the forums reported this as fixed? is this true?
Hi,
It was a similar issue also caused by the accumulators naming. This specific manifestation is related to add/migration of an existing saves does occur in v0.6.5. I proposed a fix that should resolve the issue.
Hope this helps, Z
