### ISSUE TITLE
Can add recipe of bob's material

### ISSUE THREAD

**Issue by zqr95518** [renoth/factorio-alien-module#3]
The alien ore don‘t enough of use. Can use bob's worm core?

**Comment by renoth** [comment]
Please formulate a proper question, i cannot understand what you mean.

**Comment by zqr95518** [comment]
When I have bob and this mod in one game. I can only use alien ores because there is no original worm core.

**Comment by renoth** [comment]
Ah so you mean that in bob mod there is a worm core and how do you get that worm core?

**Comment by zqr95518** [comment]
Will I mean the alien-artifact. Sorry for I use the wrong translation. Bob fide the original artifact and add a new one.

**Comment by renoth** [comment]
Ok but my mod does not alter the original artifacts in any way. There must be another issue. Alien module mod does just add alien ore to biter loot.

**Comment by zqr95518** [comment]
Can just add something such as:if there have a bob's core add a recipe like a bob's alien-artifact can melt into 10 alien's plate? Well can less than 1:10. The alien-artifacts are too many to use up.

**Comment by renoth** [comment]
I will look into it and see if i can make this change. Thanks for reporting.

**Comment by zqr95518** [comment]
=￣ω￣=

**Comment by renoth** [comment]
I updated the mod to 0.3.7 which should enable converting artifacts to ore. Please test and report.
