### ISSUE TITLE
Suggestion: Each force have their own level

### ISSUE THREAD

**Issue by unhott** [renoth/factorio-alien-module#34]
Rather than have 1 level per game it is possible to track a level per force. I think that the game automatically tracks biter kills per force in:  
https://lua-api.factorio.com/latest/LuaFlowStatistics.html

**Comment by renoth** [comment]
Good idea but then the module upgrade code would have to be rewritten completely i dont have time for that at the moment ...

**Comment by renoth** [comment]
it is actually working now with the latest version of the mod
