### ISSUE TITLE
Hypermodules destroyed if upgraded in a filtered slot

### ISSUE THREAD

**Issue by unhott** [renoth/factorio-alien-module#35]

**Comment by renoth** [comment]
What is a filtered slot?

**Comment by ChildishGiant** [comment]
If you hit middle mouse on a toolbar slot you can make it so it only every contains that item. I don't know how that works now the hotbar doesn't actually hold items.

**Comment by unhott** [comment]
I opened this here after it was reported on the mod portal. Here's what I remember: 

You can still reserve inventory slots in your inventory and on train inventory slots. If you have no open, unreserved slots, and your slot is set for level 2 module, and you hit level 3, the level 2 module stack is deleted and the game tries to insert the level 3 modules. But you have no open, unreserved inventory slots since level 2 module is not the same as a level 3, so they are deleted.

**Comment by ChildishGiant** [comment]
I suggest the slot filter is upgraded, assuming that's allowed using the API

**Comment by renoth** [comment]
Thank you for the desription i will look into it

**Comment by unhott** [comment]
I believe ccc9b70 resolves a different issue. That updates the hotbar reference, while the inventory filter is still an issue. 

To test the issue out, give yourself a stack of alien hyper modules of current level. set a filter (I believe it's middle click). fill up your inventory with other stuff. level up the alien module, watch the stack of hyper modules be destroyed. 

https://lua-api.factorio.com/latest/LuaInventory.html#LuaInventory.get_filter

**Comment by renoth** [comment]
Yes you are right, i think i fixed it with 1.0.7 now
