### ISSUE TITLE
Schalls alien tech/ slight idea

### ISSUE THREAD

**Issue by LastdragonLord** [renoth/factorio-alien-module#37]
https://mods.factorio.com/mod/SchallAlienTech
https://mods.factorio.com/mod/SchallAlienLoot
just bring up the idea that this mod and these are pretty much near like, as Schalls uses the items and allow them to spawned for the mobs. possible to check and see if things over lap?

also brought up a issue here
https://mods.factorio.com/mod/alien-module/discussion/5dbb3d1876262a000dbdedf2

**Comment by renoth** [comment]
yeah the mod seems pretty similar but i dont think they can be merged
