### ISSUE TITLE
alien kill counter crash

### ISSUE THREAD

**Issue by ChildishGiant** [renoth/factorio-alien-module#4]
when the alien kill counter reaches 40 i get a crash and it notes:
Error while running event alien-module::on_entity_died (ID 4)
LuaEntity doesn't contain key recipe.
stack traceback:
alien-module/control.lua:76: in function 'update_recipes'
alien-module/control.lua:142: in function <alien-module/control.lua:104>

**Comment by renoth** [comment]
the new version 0.4.1 should fix this issue. Thanks for reporting
