### ISSUE TITLE
Can't load game after update from 1.0.3 to 1.0.4

### ISSUE THREAD

**Issue by EleXte** [renoth/factorio-alien-module#42]
I get that error after update:
![Screenshot_61](https://user-images.githubusercontent.com/18257611/90322085-98174780-df58-11ea-982c-3c127cb13d5a.png)

I try to install mod (with load and save game without that mod) but got that error again.
On version 1.0.3 all work correctly.

Mod list:
![Screenshot_62](https://user-images.githubusercontent.com/18257611/90322123-00febf80-df59-11ea-9479-bc4e5e6ed8a7.png)
![Screenshot_63](https://user-images.githubusercontent.com/18257611/90322124-01975600-df59-11ea-8104-771793be6342.png)

**Comment by Glendening** [comment]
Different mods, same error when loading a map with 1.0.4
1.0.3 loaded successfully

**Comment by renoth** [comment]
Thanks for the report, should be fixed in 1.0.5
