### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by vizthex123** [renoth/factorio-alien-module#46]
I got this crash in Multiplayer:

No idea what caused it. I think maybe a biter destroyed a building with the alien module inside? I was AFK at the time, as was my friend.

![image](https://user-images.githubusercontent.com/31721920/90992442-6106ee80-e575-11ea-80a8-0d9cfa16e3b9.png)

**Comment by renoth** [comment]
i think i fixed this already, please test with the latest version of the mod

**Comment by renoth** [comment]
The issue would happen when the alien level goes up

**Comment by vizthex123** [comment]
Update: It crashed again, same errror:

![image](https://user-images.githubusercontent.com/31721920/91121634-d64dee80-e65d-11ea-8c0d-aafb8f79a297.png)

This time I died in singleplayer. It's a new world so I don't have any modules being used. Seems like something broke with logistics slots....? I don't have them filtered (or unlocked) though.

And here's the game log: 
[factorio-current.log](https://github.com/renoth/factorio-alien-module/files/5121281/factorio-current.log)

**Comment by renoth** [comment]
Thanks for the info, from the logfile i can see you use lots of mods, can you provide a savegame as well? The update code expects the object to be a player but it somehow is not.

**Comment by renoth** [comment]
Modlist

core
base
railloader
Robocharger
alien-biomes-hr-terrain
Armor_upgradable
beautiful_bridge_railway
belt_buffer_up
BetterBots
BigDrills
boblibrary
bullet-trails
CJs_QoL_Research_Ver1
Concretexture
Deep_Storage_Unit
DoubleFurnace
DoubleSpeedBelts
DragonIndustries
even-distribution
Factorissimo2
flib
FusionTrain
GJBigPolesAlign
improved-medium-electric-pole
MIRV
Natural_Evolution_Enemies
OmegaDrill
quickbarimportexport
SchallAlienLoot
SchallPickupTower
SchallTransportGroup
spidertron-extended
textplates
Todo-List
uranium_geiger
vtk-armor-plating
Waterfill_v17
Wood_Gasification
alien-biomes

**Comment by renoth** [comment]
Modlist from someone with the same error

all science maker
base mod
bob's assembling machines
bob's enemies
bob's functions library mod
bob's personal equipment
dragon industries - nauvis division
even distribution
factorio standard library
heracles flying carrier
hidden loot
infinite resources
luzivras factorio core
luzivras factorio power
mining drones
modular turrets
nanobots: early bots
orbital ion cannon
personal roboport mk3
power armor mk3
repair turret
schall pickup tower
shcall recharging weapons
squeak through
vanilla loaders hd
warehousing mod
waterfill

**Comment by vizthex123** [comment]
Here's my modlist:

[mod-list.zip](https://github.com/renoth/factorio-alien-module/files/5147239/mod-list.zip)

(It won't let me upload the .json, sorry)

I haven't had the crash happen again; but I also haven't been able to play a lot since my D: drive has started bugging out.

**Comment by BlueAgent** [comment]
This crash also happens in sandbox mode (where there's no character entity, just the player).
Maybe it could be prevented by checking that `player.character ~= nil` before updating the logistics slots.

**Comment by renoth** [comment]
Thanks for the hint i will try to fix it

**Comment by renoth** [comment]
Please test with 1.0.16

**Comment by BlueAgent** [comment]
Crash is fixed for me in sandbox mode. Not sure about multiplayer since no idea what triggers it but it's probably fixed too.

**Comment by Findarato** [comment]
Wanted to add I am still having this issue with the most recent version
