### ISSUE TITLE
Alien Solar panel not compatible with upgrade planer

### ISSUE THREAD

**Issue by sarr95** [renoth/factorio-alien-module#48]
upgrade planer does not show the alien solar panel under the alien loot mod tab

**Comment by renoth** [comment]
Do you have any mods installed? Especially mods that also add solar panels?

**Comment by sarr95** [comment]
i have tried it with it being the only mod installed and it still didnt work

**Comment by sarr95** [comment]
it just doesnt show up in the upgrade planner menu and upgrade planer does not find it when you have it in your hand and click on a spot in the menu

**Comment by sarr95** [comment]
i have the latest update of your mod as well

**Comment by renoth** [comment]
I tested the upgrade planner and it worked fine are you sure you are using it correctly?
![image](https://user-images.githubusercontent.com/4069007/91991794-a4aae680-ed33-11ea-9849-70e32b4d1f0c.png)

**Comment by sarr95** [comment]
i have been doing more testing and i got the problem fixed. i had a broken version of the mod thats why it didnt work as the only mod. your mod does not like factorio-extended-power mod as well factorio-extended-compound-solar . i dont know if you want to make them compatible but thanks for your time.
