### ISSUE TITLE
Medium Worm Turret

### ISSUE THREAD

**Issue by Brauhm** [renoth/factorio-alien-module#50]
Having a strange bug where if I reload the game, I suddenly get an error that medium-worm-turret max_count must be > 0.

**Comment by renoth** [comment]
Can you post the logfile?

**Comment by VerisZG** [comment]
same here

**Comment by VerisZG** [comment]
https://pastebin.com/f9PGyqus

Generally tried with many configurations but after all everything works but Alien Loot Economy, which causes the error.
To be precise, I run Factorio, add Alien Loot Economy and it crashes.

**Comment by VerisZG** [comment]
124.311 Factorio initialised
 124.317 Mods to disable:Failed to load mods: Error while loading entity prototype "medium-worm-turret" (turret): count_max must be > 0.

**Comment by VerisZG** [comment]
I think it probably happened when i changed loot probability from 100 to 1. Will test it more.

**Comment by VerisZG** [comment]
RESOLVED

data.lua

changed line 22 from

table.insert(data.raw[entityType][entityName].loot, { item = "artifact-ore", probability = probability, count_min = countMin, count_max = math.floor(countMax + 0.5) })

to

table.insert(data.raw[entityType][entityName].loot, { item = "artifact-ore", probability = probability, count_min = countMin, count_max = math.floor(countMax + 1) })

so changing the number from from 0.5 to 1 resolved the problem
