### ISSUE TITLE
Hyper module/ammo bug

### ISSUE THREAD

**Issue by HEROgold** [renoth/factorio-alien-module#54]
When the hyper level goes up while you are holding a hyper module or ammo the held item WILL NOT upgrade. please i would like a fix for this,

**Comment by renoth** [comment]
Thanks for the report. I will look into this.

**Comment by ChildishGiant** [comment]
I swear half the issues for this mod are different odd edge cases where things won't upgrade 😆

**Comment by HEROgold** [comment]
I also might have an idea for fixing dropped items, you can look and test
for specific dopped items but im not sure how to replace them, either queue
them for upgade since a level 2 does upgrade to level 4 once you lever and
make the dropped items deconstruct when you level to 3, or make use of code
to kill those modules and spawn level 3 modules in alien loot chest. Not
sure tho.

Op zo 13 sep. 2020 2:07 p.m. schreef Allie <notifications@github.com>:

**Comment by renoth** [comment]
should be fixed in 1.1.1
