### ISSUE TITLE
When reaching Level 101 on the hyper module, the world crashes

### ISSUE THREAD

**Issue by SolonelyCapybara** [renoth/factorio-alien-module#57]
its fine if i cannot get higher than 100, 100 is plenty fast. but i need to still be able to kill enemies for other mod's loot. you can speed up leveling in the cnfg, but not disable it.  Is there a way to turn off leveling up?
EDIT- I went into the file and changed the minimum value to 0, and then set the value to zero, and while its a heck of a lot slower, I don't think it's a permanent fix.
EDIT2- I once again went in and made the number negative, by a tiny bit. This resulted in my module level instantly getting set to 1. However it was only a GUI thing and the actual modules are still lvl 100. I think this has solved my problem, but ya know, still an issue. I love the mod and will probably use it in all my modded endeavors in the future!

**Comment by renoth** [comment]
What value did you edit? Do you have a stacktrace of the error?

**Comment by renoth** [comment]
Probably fixed in 1.1.0 please test

**Comment by SolonelyCapybara** [comment]
Yes! Running 1.1.1, it snapped back to an even 100 and isn't going up or crashing. Thank you so much for you help!
