### ISSUE TITLE
Crash: Invalid item stack read on level up

### ISSUE THREAD

**Issue by Miner239** [renoth/factorio-alien-module#59]
![image](https://user-images.githubusercontent.com/4686046/94343297-5bec0200-0041-11eb-8102-6048488c0424.png)

Please, please, add validity check on everything control script touches...

**Comment by renoth** [comment]
Thanks for the report, i added a validity check.

**Comment by ResidentOfKill** [comment]
Still not working 
![adwwdasd](https://user-images.githubusercontent.com/66139191/94350126-71662980-004b-11eb-9812-28e81239bcf1.PNG)

**Comment by renoth** [comment]
Please test with 1.1.4
