### ISSUE TITLE
error after updating

### ISSUE THREAD

**Issue by mattnotl33t** [renoth/factorio-alien-module#60]
got an error after updating the mod. after a period of time the upgrading hypermodule level via kill count caused this error

> The mod Alien Loot Economy (1.1.1) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event alien-module::on_nth_tick(120)
> LuaItemStack API call when LuaItemStack was invalid for read.
> stack traceback:
> 	__alien-module__/control.lua:95: in function 'update_modules'
> 	__alien-module__/control.lua:375: in function <__alien-module__/control.lua:331>
> stack traceback:
> 	[C]: in function '__index'
> 	__alien-module__/control.lua:95: in function 'update_modules'
> 	__alien-module__/control.lua:375: in function <__alien-module__/control.lua:331>

**Comment by renoth** [comment]
Thanks for the report, it is the same as in #59, should be fixed in 1.1.2
