### ISSUE TITLE
Alien Hyper Magazine gets deleted on level up when viewing chest

### ISSUE THREAD

**Issue by Ramses-II** [renoth/factorio-alien-module#63]
Hey,
we have encountered a problem on our multiplayer server. 
When the hypermodule level updates and you are viewing a chest that has magazines in it, they get deleted. I think the inventory was full at these times. Recurring issue on levelup from 34 to 35 and from 35 to 36, thats where we are right now (without any magazines, yey)
Factorio Version 1.0
Mod Version 1.1.4.
Cheers, Ramses303

**Comment by renoth** [comment]
Should be fixed in 1.2.4, please test
