### ISSUE TITLE
freezing when levelup

### ISSUE THREAD

**Issue by Aideln** [renoth/factorio-alien-module#66]
first time, I think problem in game.
but on the third restart, I found out that there was a problem with the mod.
It all happened when I leveled up.
I don't want to exclude this mod. because it is very nice.
I attach a save file and mod list in case it might help.

[mods.zip](https://github.com/renoth/factorio-alien-module/files/5506697/mods.zip)
[_autosave1.zip](https://github.com/renoth/factorio-alien-module/files/5506694/_autosave1.zip)

**Comment by ChildishGiant** [comment]
Is this the same issue as #31?

**Comment by unhott** [comment]
It appears so. 
It is worth revisiting if that is still the current behavior. 

It is solvable as I demonstrated by using a chunk iterator, guaranteeing 'eventual' upgrade of all entities. I underestimated how many surfaces that some people play with in terms of mods like factorissimo. That is fixable as well by just making a surface iterator, which If I recall correctly I also provided. But I'm not great w/ github so I don't know if it was ever taken seriously.

**Comment by renoth** [comment]
It only happens on levelup so i think it is tolerable.

**Comment by HEROgold** [comment]
Well when multiple issues have been reported about the hang, that would tell me that it in fact IS NOT TOLERABLE.

**Comment by renoth** [comment]
> Well when multiple issues have been reported about the hang, that would tell me that it in fact IS NOT TOLERABLE.

Well if the Factorio Developers would provide an API that would solve this issue easily i would have implemented it. If you think it is not tolerable then stop using the mod or provide a pull request.
