### ISSUE TITLE
Compatibility with unlimited productivity mod

### ISSUE THREAD

**Issue by HEROgold** [renoth/factorio-alien-module#67]
So when i load with both these mods on i get this error, when i load with just one on i have no issue, either loot economy or unlimited prod. 

![afbeelding_2020-11-22_122525](https://user-images.githubusercontent.com/21345384/99902392-cc1fa880-2cbd-11eb-869c-f7eff5963c7e.png)

**Comment by renoth** [comment]
Incompatibility added to info.json

**Comment by BlueAgent** [comment]
@HEROgold 
I tried loading the two mods together and they work just fine with each other. Was using:

Unlimited Productivity v1.4.2
Alien Loot Economy v1.2.4 (edited `info.json` to remove Unlimited Productivity from the incompatibility)

Are you sure that you ONLY had those two mods installed and not some onother some other mods?
Sometimes the crashing mod(s) are not where the true bug lies as well.
