### ISSUE TITLE
Incompatible with "Biter factions"

### ISSUE THREAD

**Issue by WeetLee** [renoth/factorio-alien-module#70]
Hi,

there is an issue that made the mod incompatible with "Biter factions". You are looking for a faction called ennemy to know if you need to increase killcount, however, the mod sort biters into different factions called "biter_faction_xxx" (as you can see in the source code below)
> game.create_force("biter_faction_"..i)

https://github.com/renoth/factorio-alien-module/blob/214c4572f674139bb43e6143da1d4c3b767fe8cc/alien-module/control.lua#L325

However, that could be an other issue to fix the faction filter to include these new factions, as biters fights quite often and kills eachothers.
If the factorio API allows to know which faction killed the entity, it could be solved. If not, you should add an incompatibility whith said mod in your mod description.

**Comment by renoth** [comment]
Incompatibility added to info.json
