### ISSUE TITLE
Hyper Modules disappear when trying to Evenly Distribute

### ISSUE THREAD

**Issue by cacomixl8** [renoth/factorio-alien-module#71]
Below is a copy of the report I also made to the author of Even Distribution. There are no error codes.

Upon evenly distributing hyper modules added by Alien Loot Economy mod, I lost a incomplete stack of 37 hyper modules. 2 modules were inserted into the last A2 selected and the other 35 were lost. The onscreen popup showed 37 modules consumed on the last machine and no popups on the other 9 machines.

I'm not sure whose responsibility is for compatibility, and have not delved into the scripts at all.

Thanks for the great mod :)

**Comment by renoth** [comment]
I think you should contact Evenly Distribute mod author
