### ISSUE TITLE
Bug - Game freezes during level up alien modules

### ISSUE THREAD

**Issue by Hitwood** [renoth/factorio-alien-module#73]
I allready disabled the mods Bobs library, even distribution and schall pickup tower

**Comment by renoth** [comment]
this is known and intentional.

**Comment by renoth** [comment]
See #66

**Comment by Hitwood** [comment]
The game not only freezese for some seconds. It hung up

Am Di., 26. Jan. 2021 um 13:10 Uhr schrieb renoth <notifications@github.com

**Comment by renoth** [comment]
I see, how big is your savegame? Do you have a huge base?

**Comment by Hitwood** [comment]
39MB

renoth <notifications@github.com> schrieb am Di., 26. Jan. 2021, 14:19:

**Comment by renoth** [comment]
Sounds not too big, should freeze for some time but not forever ...

**Comment by Hitwood** [comment]
Waiting now for 7 minutes

renoth <notifications@github.com> schrieb am Di., 26. Jan. 2021, 14:28:

**Comment by Hitwood** [comment]
Okay Just starts to work again. 😛
BTW thank you for your great mod !

I would get crazy during homeoffice, if i would not be able to play
factorio...

Stay healthy

Hitwood <hitwood76@gmail.com> schrieb am Di., 26. Jan. 2021, 14:31:

**Comment by renoth** [comment]
MAybe get a faster PC ;)
