### ISSUE TITLE
Add configuration option to include the alien ore making recipe for players.

### ISSUE THREAD

**Issue by BrotherLeon** [renoth/factorio-alien-module#74]
My friend and I were playing on a save with this mod, then after we updated to the newer version for 1.1, the alien ore recipe was gone. This might be a bug or it might be intentional, but my friend and I were mighty rumbled by this change. If it was intentional, please add a config option to allow for that alien ore making recipe to be used. It can still be off by default. If it wasn't intentional, please fix it so the recipe is back. Or add the config option, too, anyways.

have a good day.

**Comment by unhott** [comment]
I haven't followed the updates, so I don't know if it was removed or not. 

It could be an issue with a failed migration-- that is, the recipe changed somehow and the migration script did not successfully enable the recipe for an in-progress save. You can potentially test this by starting a new game with the same mods loaded and checking if the recipe exists. If the recipe is still in the game but just not successfully activated, there are lua scripts you can run in game to enable it.

**Comment by BrotherLeon** [comment]
tried a new game, and the recipe still wasn't there

**Comment by renoth** [comment]
There is already such an option. Maybe it is disabled.
