### ISSUE TITLE
Add a per player config option to hide Hypermodule Level GUI

### ISSUE THREAD

**Issue by SethWilliamson** [renoth/factorio-alien-module#78]
Please add a per-player config option to hide the GUI at the top of the screen. Some players prefer a minimal user interface. Giving them the option would be a nice quality of life addition to the mod. I would personally like to turn it off after reaching level 100 since it isn't giving me any useful information anymore.

**Comment by unhott** [comment]
I'm not saying they shouldn't do this, but check out: https://mods.factorio.com/mod/guiManager

**Comment by renoth** [comment]
@unhott Great stuff, thanks for the hint, will close this issue

**Comment by renoth** [comment]
I also love that your example is with this mod :D
