### ISSUE TITLE
Ore not dropping while paired with only rampant mod

### ISSUE THREAD

**Issue by schmidtr** [renoth/factorio-alien-module#8]
After updating the mod, my server we have noticed that the enemies do not drop the alien ore and we are running only the rampant mod, we were possibly looking into running NE but that would alter what we have setup currently, can you please look into why the rampant mod enemies are not dropping ore.

**Comment by renoth** [comment]
The relevant questions would be: 

- Which version did you update? Rampant or Alien Loot Economy? 

- From which version to which version? 

- Did Rampant Enemies drop loot before the update?

**Comment by schmidtr** [comment]
and after reverting to the older version of 0.4.7 all the enemies drop the alien ore as they were prior.

**Comment by renoth** [comment]
Does Rampant have its own enemies or does it use the vanilla enemies? Looking at the Rampant code it seems that Rampant does introduce new enemies that should not work with either Alien Loot Economy version.

**Comment by schmidtr** [comment]
I can assure you it worked with the previous version of the mod. I know it uses a mix of both, but we use rampant to mainly increase the spawn of vanilla enemies. I had reverted it killed some enemies and gotten alien ore, quit and updated to the new version killed the same batch of enemies (over 50) worms and spawners and got nothing.

**Comment by renoth** [comment]
Ok thanks for the report, i will look into it this week, in the meantime you can revert to 0.4.7 to continue getting loot from enemies.

**Comment by renoth** [comment]
0.4.8 does only improve the mod for users of NE mod so you dont miss anything here.

**Comment by renoth** [comment]
i uploaded 0.4.9 - please Test, vanilla biters should drop loot again in rampant and everywhere else, surprised you are the first one to notice. Thank you for the bug report!

**Comment by schmidtr** [comment]
Is it possible to also implement the rampant enemies such as the acid spitter workers and such? If its super lengthy im not super worried about it.
Thanks ill test it when I can!

**Comment by renoth** [comment]
I published Version 0.4.10 that should also enable Loot from Custom Rampant enemies, though not very much at low levels. Please Test and report, Thanks!
