### ISSUE TITLE
Suggestion: Can the cost of Alien 

### ISSUE THREAD

**Issue by vfinn** [renoth/factorio-alien-module#82]
Can the cost of Alien Plates escalate for each FORCE, rather than globally?
I support this mod in Brave New Oarc mod, and run a server hosting Brave New Oarc with Alien Modules  (Search Maroons to find it). But Oarc has each team in a separate force, with a separate spawn location. It's unfair that the first persons to join get the most amount of modules cheaply.  I'd like it to be even for each force, where based on the quantity of alien ore they process the cost of the modules/plates increase as it does now, but separately for each force.

It seems that global.modulelevel, global.currentmodulelevel and global.killcount  could be used as array items where 
global.modulelevel = {}

Then update which ever global.modulelevel[player.force.name] causes the kill.

Let me know if you have time for this, if not and you might consider incorporating a branch modification, I can make the changes.

Thank you

**Comment by renoth** [comment]
Yes i would do a review, but i think there are people more experienced with LUA that made PRs previously to this repo.
I would not know how to test the changes except in singleplayer so i will have to take your word that it works ;)

**Comment by renoth** [comment]
Great news! Looking forward to the PR

**Comment by renoth** [comment]
There seem to be no changes pushed to your repository so far
![image](https://github.com/renoth/factorio-alien-module/assets/4069007/6942add6-3894-4583-9a88-864224da14c9)

**Comment by renoth** [comment]
You need to commit the changes and then push them to your fork of the repository. Afterwards we can open a pull request to this repository.

If you are coming from subversion you have to be aware that git commit does not PUSH the changes to the origin (github). You not only need to commit locally but also push your commit to the respository defined as origin. (git push)

**Comment by renoth** [comment]
you can also push from the console and see if you get a usable error message.

**Comment by renoth** [comment]
One question: What happens if i load a saved game from Version 1.3.0?

**Comment by renoth** [comment]
When i load my 1.3 save i get the following error, seems like i need to add a migration
![image](https://github.com/renoth/factorio-alien-module/assets/4069007/43a8aa43-6a0d-4bb9-8683-941449d9cb9b)

**Comment by renoth** [comment]
Added a migration and released 1.4.0. Thank you very much for the implementation and idea!

**Comment by renoth** [comment]
There is one problem: If i play singleplayer the module level does not go up and it is caused by this line:

![image](https://github.com/renoth/factorio-alien-module/assets/4069007/ef85dcea-fa5d-4133-a429-9600c4a10301)

If i remove it, it works fine. Do you know why this is added?

**Comment by renoth** [comment]
Fixed this and released 1.4.1 without that line. If it is needed for multiplayer please provide a fix where both modes are possible.

**Comment by renoth** [comment]
Thanks for the fix, i will do this when i have the time (probably tomorrow)
