### ISSUE TITLE
1.4.1 fails on oarc

### ISSUE THREAD

**Issue by vfinn** [renoth/factorio-alien-module#84]
I didn't get a chance to test 1.4.1 until late last night.
Oarc fails with crash in control line 382 - because "player" is not initialized. Can you add this at top of control.lua?

```
script.on_init(function()
	initVariables()
	init_gui()
	verifyCountersForForce("player")    -- initialize single player
end)
```

**Comment by renoth** [comment]
Should be fixed in 1.4.2, please test
