### ISSUE TITLE
2 issues - 1) crash due to player dieing and biters dieing after his death.   2) Players perform a restart and want kill count to go to zero 

### ISSUE THREAD

**Issue by vfinn** [renoth/factorio-alien-module#85]
If you'll post the update. I'll make these two changes.
#1 issue is a bug - but a fairly rare condition that could happen when a character is fighting with turret backup. This causes a crash in on_entity_died. I'll setup the test scenario to cause the crash, then add the fix.
#2 - I allow a player to restart in Brave New Oarc, or if they lose their main roboport they are forced to restart. I'd like to build a remote interface to enable another mod to reset killcounts/module level for a force.  

Let me know what you think. I could get this done pretty quickly and will do a PR.

**Comment by renoth** [comment]
The latest version is released, you can create PRs for the fixes
