### ISSUE TITLE
crash with space exploration

### ISSUE THREAD

**Issue by maxxcz69** [renoth/factorio-alien-module#86]
this is error after starting the game:

Error while running event alien-module::on_nth_tick(600)
__alien-module__/control.lua:383: attempt to compare nil with number
stack traceback:
	__alien-module__/control.lua:383: in function <__alien-module__/control.lua:371>

**Comment by renoth** [comment]
Thanks for reporting, was this an existing save when you updated the Mod to Version > 1.4.0
Can you run the following command in console before the crash: 'log_am'

**Comment by renoth** [comment]
is maybe fixed in 1.4.3
