### ISSUE TITLE
Why new tab?

### ISSUE THREAD

**Issue by SuperSandro2000** [renoth/factorio-alien-module#9]
Why does the mod add a new tab to the crafting screen? They would have fit in the ones we have perfectly.

**Comment by renoth** [comment]
Because i felt like it.

**Comment by SuperSandro2000** [comment]
Yeah then you will be added to my shame mod if I decide to use it

**Comment by renoth** [comment]
Yeah great, thanks. You see if you would have created a PR or something constructive instead of just complaining about something "Why is X not Y?" i might have considered it, thanks for your feedback though, but no i wont change that because i feel the way it is now suits the theme of the mod best.
