### ISSUE TITLE
Error on start with new version

### ISSUE THREAD

**Issue by askdata01** [renoth/factorio-alien-module#94]
Updated the mod today and Factorio crashed on start with the following message:
The mod Alien Loot Economy (1.4.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event alien-module::on_load()
__alien-module__/control.lua:66: attempt to index field 'currentmodulelevel' (a number value)
stack traceback:
	__alien-module__/control.lua:66: in function 'verifyCountersForForce'
	__alien-module__/control.lua:11: in function <__alien-module__/control.lua:10>

**Comment by Mr-Train-1** [comment]
I have also had the same issue

**Comment by valwong3** [comment]
the issue still hasnt been fixed, still having the same issue

**Comment by renoth** [comment]
please test with 1.4.9

**Comment by askdata01** [comment]
Seems to be working now.  Loaded a saved game with the updated mod.

Thanks!

Steve Williamson
